
	// Onetwo.idl : IDL source for Onetwo.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (Onetwo.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
[
	uuid(1FFFBDF5-3FA1-4B17-82EA-CEDDB7EA171C),
	version(1.0),
	helpstring("Onetwo 1.0 Type Library")
]
library OnetwoLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};

	